export const ProjectStatus = {
    BASIC_STUDIES: "BASIC STUDIES",
    DESIGN_IN_PROGRESS: "DESIGN IN PROGRESS",
    UNDER_REVIEW: "UNDER REVIEW",
    CHANGE_REQUESTED: "CHANGE REQUESTED",
    CHANGE_PENDING: "CHANGE PENDING",
    REJECTED: "REJECTED",
    APPROVED: "APPROVED",
}